// Bower Digital — shared project data.
// Loaded before portfolio.jsx and work.jsx via <script> order.
// Exposes window.PROJECTS for consumption by both pages.

window.PROJECTS = [
  {
    slug: "crossman-crafts",
    name: "Crossman Crafts",
    kind: "Portfolio & ecom",
    year: "2026",
    category: "website",
    visibility: "public",
    href: "https://crossmancrafts.vercel.app/",
    blurb: "Professional landing page for Cole Crossman.",
    featured: true,
  },
  {
    slug: "infradex",
    name: "Infradex",
    kind: "Market data",
    year: "2026",
    category: "website",
    visibility: "public",
    href: "https://infradex.vercel.app/",
    blurb: "Ontario infrastructure data platform that surfaces geospatial, permit, and property data for the province.",
    featured: true,
  },
  {
    slug: "landledger",
    name: "Land Ledger",
    kind: "Real estate CRM",
    year: "2026",
    category: "tool",
    visibility: "private",
    href: null,
    blurb: "Custom CRM platform that enables agent workflows and replaced all previously used sales tools.",
    longBlurb: "Custom CRM platform that enables OpenClaw/Hermes agent workflows and replaced all previously used sales tools. Built as internal tooling for a real estate acquisition team — pipeline management, automated outreach, and deal tracking in one place.",
    featured: true,
  },
  {
    slug: "project-four",
    name: "Project Four",
    kind: "E-commerce site",
    year: "2024",
    category: "website",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — full-stack storefront with inventory management and Stripe checkout.",
    featured: false,
  },
  {
    slug: "project-five",
    name: "Project Five",
    kind: "Client dashboard",
    year: "2024",
    category: "webapp",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — internal reporting tool for a mid-size team.",
    featured: false,
  },
  {
    slug: "project-six",
    name: "Project Six",
    kind: "CLI utility",
    year: "2025",
    category: "tool",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — developer tool that automates a repetitive deployment workflow.",
    featured: false,
  },
];
