// Bower Digital — shared project data.
// Loaded before portfolio.jsx and work.jsx via <script> order.
// Exposes window.PROJECTS for consumption by both pages.

window.PROJECTS = [
  {
    slug: "crossman-crafts",
    name: "Crossman Crafts",
    kind: "Portfolio & shop",
    year: "2026",
    category: "website",
    visibility: "public",
    href: "https://crossmancrafts.vercel.app/",
    blurb: "Professional landing page for Cole Crossman.",
    featured: true,
  },
  {
    slug: "infradex",
    name: "Infradex",
    kind: "Market data platform",
    year: "2026",
    category: "webapp",
    visibility: "public",
    href: "https://infradex.vercel.app/",
    blurb: "Ontario infrastructure data platform — surfaces geospatial, permit, and property data for the province.",
    featured: true,
  },
  {
    slug: "land-ledger",
    name: "Land Ledger",
    kind: "Real estate CRM",
    year: "2026",
    category: "webapp",
    visibility: "private",
    href: null,
    blurb: "Custom CRM that replaced a full stack of real-estate sales tools.",
    longBlurb: "Custom CRM platform built end-to-end for a Toronto-area real estate team. Replaced their full stack of sales tools — contact management, listings, deal pipeline — with one tailored web app. Built solo.",
    featured: true,
  },
  {
    slug: "project-four",
    name: "Project Four",
    kind: "E-commerce site",
    year: "2024",
    category: "website",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — full-stack storefront with inventory management and Stripe checkout.",
    featured: false,
  },
  {
    slug: "project-five",
    name: "Project Five",
    kind: "Client dashboard",
    year: "2024",
    category: "webapp",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — internal reporting tool for a mid-size team.",
    featured: false,
  },
  {
    slug: "project-six",
    name: "Project Six",
    kind: "CLI utility",
    year: "2025",
    category: "tool",
    visibility: "public",
    href: "#",
    blurb: "Placeholder — developer tool that automates a repetitive deployment workflow.",
    featured: false,
  },
];
